template(
    name="cgnat"
    type="string"
    string="/var/log/cgnat/%hostname%/%$year%/%$month%/%$day%/server-%$hour%.log"
)

if (
	$programname == "cgnat"
	and
	$hostname contains "CGNAT"
) then {
    action(
        type="omfile"
        dynaFile="cgnat"
        createDirs="on"
        dirCreateMode="0750"
        fileCreateMode="0640"
        dirOwner="root"
        dirGroup="daniel"
        fileOwner="root"
        fileGroup="daniel"
    )
    stop
}
